(function(){var g=true,s=null,t=false,w=document,x=window.i={},y=navigator.userAgent.toLowerCase(),z=(y.match(/.+(?:rv|it|ra|ie)[\/: ]([\d.]+)/)||[])[1],aa=/webkit/.test(y),A=/opera/.test(y),C=/msie/.test(y)&&!/opera/.test(y),E=!!y.match(/applewebkit.*mobile.*/),F=/iPad/i.test(y),G=t,I=t,J=[];function K(){if(!I&&(I=g,J)){for(var a=0;a<J.length;a++)J[a].call(window,[]);J=[]}}function ba(){var a=K,b=window.onload;window.onload=typeof window.onload!="function"?a:function(){b&&b();a()}}
function N(){if(!G){G=g;w.addEventListener&&!A&&w.addEventListener("DOMContentLoaded",K,t);C&&window==top&&function(){if(!I){try{w.documentElement.doScroll("left")}catch(a){setTimeout(arguments.callee,0);return}K()}}();A&&w.addEventListener("DOMContentLoaded",function(){if(!I){for(var a=0;a<w.styleSheets.length;a++)if(w.styleSheets[a].disabled){setTimeout(arguments.callee,0);return}K()}},t);if(aa){var a;(function(){if(!I)if(w.readyState!="loaded"&&w.readyState!="complete")setTimeout(arguments.callee,
0);else{if(a===void 0){for(var b=w.getElementsByTagName("link"),e=0;e<b.length;e++)b[e].getAttribute("rel")=="stylesheet"&&a++;a+=w.getElementsByTagName("style").length}w.styleSheets.length!=a?setTimeout(arguments.callee,0):K()}})()}ba()}}x.ready=function(a){N();I?a.call(window,[]):J.push(function(){return a.call(window,[])})};N();var O,P="wumii-hook",R="wurl",ma="wtitle",U=t,V=(typeof wumiiDebugServer!="undefined"?wumiiDebugServer:"http://app.wumii.com")+"/ext/";
if(!C&&!na()&&(typeof wumiiEnableCustomPos=="undefined"||!wumiiEnableCustomPos||w.getElementById("wumiiDisplayDiv")))try{oa(),U=g}catch(pa){}x.ready(function(){U||(U=g,oa())});function na(){if(/\.jimdo\.com$/.test(location.hostname))return g;for(var a=w.getElementsByTagName("link"),b=0;b<a.length;b++){var e=a[b].href;if(e.indexOf("http://u.jimdo.com/")!=-1||e.indexOf("http://s.jimdo.com/")!=-1)return g}return t}
function oa(){function a(){O=qa(b);if(O.length==1){var a=O[0];if(a.h())a.c.style.display="none";W(a.b(),a.d(),a.a)}else X(),ra()}var b=sa();if(b.length==0){var e=w.createElement("div");e.className=P;b.push(e);if(na()){if(!/\d{4}\/\d{2}\/\d{2}/.test(w.location.href))return;for(var c=w.getElementById("content_area").getElementsByTagName("div"),h=0;h<c.length;h++)if(c[h].id.indexOf("cc-matrix")!=-1){c[h].appendChild(e);break}}else{var l=w.getElementById("wumiiRelatedItems");if(typeof wumiiParams!="undefined"&&
wumiiParams.indexOf("pf=CNBLOGS")!=-1)(function(){var b=w.getElementById("MySignature");if(b.length==0||b.innerHTML=="")setTimeout(arguments.callee,25);else{for(var b=b.children,c=0;c<b.length;c++)if(b[c].id=="wumiiRelatedItems"){l=b[c];break}l&&(l.parentNode.insertBefore(e,l),a())}})();else{if(!l)return;if((c=l.getAttribute("src"))&&c.indexOf("pf=Z-Blog")!=-1||typeof wumiiParams!="undefined"&&wumiiParams.indexOf("pf=Z-Blog")!=-1)return;l.parentNode.insertBefore(e,l)}}}a()}
function sa(){for(var a=w.getElementsByTagName("div"),b=[],e=0;e<a.length;e++)a[e].className==P&&b.push(a[e]);return b}
function qa(a){function b(a){function b(a,e){for(var c=a.c.getElementsByTagName("input"),h=0;h<c.length;h++)if(c[h].getAttribute("name")==e)return c[h].getAttribute("value");return""}this.c=a;this.a=this.e=t;this.j=function(){return this.c};this.l=function(){return this.e};this.f=function(){this.e=g};this.k=function(){return this.a};this.b=function(){var a=b(this,R);/^\//.test(a)&&typeof wumiiSitePrefix!="undefined"&&wumiiSitePrefix?a=wumiiSitePrefix+a:/^http/.test(a)||(a="");!a&&typeof wumiiPermaLink!=
"undefined"&&wumiiPermaLink&&(a=wumiiPermaLink);return!a?(this.a=g,location.href):a};this.d=function(){var a=b(this,ma);!a&&typeof wumiiTitle!="undefined"&&(a=wumiiTitle);return a?a:w.title};this.h=function(){var a=this.b().toLowerCase();return a.indexOf("http://big5.ifeng.com/gate/big5/blog.ifeng.com/")==0||a.indexOf("http://www.umiwi.com/")==0}}for(var e=[],c=0;c<a.length;c++)e[c]=new b(a[c]);return e}
function W(a,b,e){var c="&num=4&mode=3&v="+encodeURIComponent("")+("&pf="+encodeURIComponent(""))+("&theme="+encodeURIComponent("")),a=V+"related_items_v2?url="+encodeURIComponent(a)+"&title="+encodeURIComponent(b)+"&fromlocation="+encodeURIComponent(e);(b=w.referrer)&&(a+="&refer="+encodeURIComponent(b));typeof wumiiParams!="undefined"?(wumiiParams.indexOf("pf=WordPress")!=-1&&(wumiiParams=wumiiParams.replace(/&#038;/g,"&")),a+=wumiiParams):a+=c;typeof wumiiSitePrefix!=
"undefined"&&wumiiSitePrefix&&(a+="&sitePrefix="+encodeURIComponent(wumiiSitePrefix));c=w.createElement("script");c.type="text/javascript";c.src=a;w.getElementsByTagName("head")[0].appendChild(c)}
function X(){for(var a=0;a<O.length;a++){var b=O[a],e;if(b.e)e=t;else{e=window.innerHeight||w.documentElement.clientHeight;for(var c=b.c,h=0;c!=s;)h+=c.offsetTop,c=c.offsetParent;c=h-(window.pageYOffset||w.documentElement.scrollTop||w.body.scrollTop||0);e=c>=-400&&c<=800+e}e&&(b.f(),W(b.b(),b.d(),b.a))}}
function ra(){if(window.addEventListener)window.addEventListener("scroll",function(){X()},t),window.addEventListener("resize",function(){X()},t);else if(window.attachEvent)window.attachEvent("onscroll",function(){X()}),window.attachEvent("onresize",function(){X()});else if(w.getElementById)window.onload=function(){for(var a=0;a<O.length;a++)wumiiDiv.f(),W(wumiiDiv.b(),wumiiDiv.d(),wumiiDiv.a)}}
function Y(a,b,e){a.addEventListener?a.addEventListener(b,e,t):a.attachEvent?a.attachEvent("on"+b,function(){e.apply(a,arguments)}):a["on"+b]=e}function Z(a,b,e){var c=(b=b==="mouseenter")?"fromElement":"toElement";Y(a,b?"mouseover":"mouseout",function(b){var b=b||window.event,l=b.target||b.srcElement,b=b.relatedTarget||b[c];(a===l||(a.contains?a.contains(l):a.compareDocumentPosition(l)&16))&&!(a.contains?a.contains(b):a.compareDocumentPosition(b)&16)&&e()})}
function Aa(a,b){function e(a,e){var c=(a.lastElementChild||a.lastChild).offsetWidth,l=c/15,h=e=="out",u=h?0:-c;B=g;(function(){if(u<=0&&u>=-c)h?u-=l:u+=l,a.style[b]=u+"px",setTimeout(arguments.callee,1);else{var e="";h?(m=t,e="0 0"):(m=g,e="-"+(Q+1)+"px 0");B=t;u=h?-c:0;a.style[b]=u+"px";a.children[0].children[0].style.backgroundPosition=e}})()}function c(a){var b=a.className=="wumii-popup-relatedItems",c=w.documentElement.clientHeight||w.body.clientHeight,l=w.documentElement.scrollHeight||w.body.scrollHeight;
b&&l<c&&e(a,"in");var h=a.style.position,u=a.offsetTop,M=window.onscroll;window.onscroll=function(){M&&M();var c=window.pageYOffset||w.documentElement.scrollTop||w.body.scrollTop;if(h=="absolute")a.style.top=c+parseInt(u)+"px";if(!B&&!L&&b){var l=w.documentElement.clientHeight||w.body.clientHeight,H=(w.documentElement.scrollHeight||w.body.scrollHeight)*2/3;c+l>=H&&!m?e(a,"in"):c+l<H&&m&&e(a,"out")}}}function h(a){Y(a.children[0].children[0],"click",function(){B||(L=g,m?e(this.parentNode.parentNode,
"out"):e(this.parentNode.parentNode,"in"))})}function l(a){Z(a,"mouseenter",function(){!B&&!m&&!m&&e(a,"in")})}var B=t,m=t,L=t,Q=a.children[0].offsetWidth;this.g=function(){h(a);F||l(a);c(a)}}
window.wumiiRelatedItems=function(a,b,e,c,h){function l(f,a){var d=w.getElementById("wumiiData");d&&(d.parent||d.parentNode).removeChild(d);var d=w.getElementsByTagName("head")[0],j=w.createElement("script");j.setAttribute("type","text/javascript");j.setAttribute("id","wumiiData");j.setAttribute("src",f);d.appendChild(j);a&&a()}function B(f){var a=f.children[0];a.innerHTML=parseInt(a.innerHTML)+1;f.onmouseover=function(){};f.onmouseout=function(){};f.style.backgroundPosition="-178px 0";fa=g}function m(f,
a){return f.currentStyle?f.currentStyle[a]:w.defaultView.getComputedStyle(f,s)[a]}function L(f){var ea=t;Y(f.children[1],"click",function(){if(!fa&&(l(V+"like?ts="+(new Date).getTime()+"&url="+encodeURIComponent(D),function(){B(f)}),!(b=="true"||e=="false"))){var d=w.getElementById("wumiiLoginTipsDiv");if(d){var j=d.style;if(ea)j.display="block";else{ea=g;j.left="-9999px";j.display="block";var c=d.parentNode.parentNode;if(m(c,"overflow")=="hidden")c.style.overflow="visible";var c=f.offsetLeft,p=f.offsetTop,
k=parseInt(f.style.width),o=d.offsetHeight,n=(parseInt(j.width)-k)/2;c>=n?j.left=c-n+"px":(j.left=c+"px",n=d.children[1].style,n.margin="0px",n.left=c+k/2-10+"px");p-=o;typeof w.body.style.maxHeight!="undefined"&&(p-=20);j.top=p+"px";Y(w.getElementById("wumiiCloseLoginTips"),"click",function(){j.display="none"});if(w.getElementById("wumiiBindingBtns")){var q=s;Y(w.getElementById("wumiiLoginTipsContent"),"click",function(f){f=f||window.event;f=f.target||f.srcElement;if(f.nodeName=="A")if(f.id=="wumiiNoTipsBtn")l(V+
"login/disable"),d.parentNode.removeChild(d);else if(f.className=="wumii-reg-btn"||f.className=="wumii-binding-btn")q!=s&&clearInterval(q),q=setInterval(function(){l(V+"login/check?url="+encodeURIComponent(a))},1500),window.loginedCheck=q})}}}}})}function Q(f){Y(f,"click",function(){var f=V+"recommendations?ts="+(new Date).getTime()+"&url="+encodeURIComponent(D);w.getElementById("wumiiLoading").style.display="inline";typeof wumiiSitePrefix!="undefined"&&(f+="&sitePrefix="+encodeURIComponent(wumiiSitePrefix));
l(f)})}function ca(){return"http://static.wumii.cn/resources/images/related_item_default/"+(Math.floor(Math.random()*100)+1)+".jpg"}function da(f){var a=window.JSON;return a&&a.parse?a.parse(f):eval("("+f+")")}function ta(f){var f=f||window.event,a={x:0,y:0};if(f.type=="touchstart"&&f.touches.length>0)return f=f.touches[0],{x:f.pageX,y:f.pageY};if(f.pageX||f.pageY)return{x:f.pageX,y:f.pageY};if(typeof window.pageXOffset!="undefined")a.x=window.pageXOffset,a.y=window.pageYOffset;else if(typeof document.documentElement!=
"undefined")a.x=document.documentElement.scrollLeft,a.y=document.documentElement.scrollTop;else if(typeof document.body!="undefined")a.x=document.body.scrollLeft,a.y=document.body.scrollTop;a.x+=f.clientX;a.y+=f.clientY;return a}function ua(f){f=f.match(/(?:[?|&])t=([^&]+)/);return f==s?"":f[1]}function va(f,a,d){typeof d=="number"&&(d=d.toString());for(var j=d.length,f=Math.round(f)+d.substring(j-3),a=Math.round(a)+d.substring(j-4),f=f.length+f+a,a=f.length,d=d.split("").reverse().join(""),j=[],
b=[],c=0;c<a;c++){var k=f.charCodeAt(c)-"0".charCodeAt(0)+3,e=c<d.length?d.charCodeAt(c)-"0".charCodeAt(0):0;j.push(String.fromCharCode("a".charCodeAt(0)+k+e));b.push(String.fromCharCode("z".charCodeAt(0)-k-e))}return j.join("")+b.join("")}function u(a,b){var d="touchstart"in window,j=d?"touchend":"mouseup";Y(a,d?"touchstart":"mousedown",function(a){var f=this.getAttribute("href"),d=this.getAttribute("origLink"),c=this.getAttribute("redirectUrl");d||(this.setAttribute("origLink",f),Y(this,j,function(){var a=
this;setTimeout(function(){a.setAttribute("href",a.getAttribute("origLink"))},50);if(C&&/6.0|7.0|8.0/.test(z))a.getAttribute("target")=="_blank"?window.open(a.getAttribute("href")):location.href=a.getAttribute("href")}),d=this.getAttribute("origLink"));c?(a=ta(a),f=ua(decodeURIComponent(c)),c+="&oc="+va(a.x,a.y,f)):c="http://app.wumii.com/ext/redirect?url="+encodeURIComponent(d)+"&ts="+(new Date).getTime()+"&from="+b+"&ref=relatedItems";this.setAttribute("href",c)})}function M(a){Y(a,"mouseover",
function(){this.style.borderTopColor="#ffaf00"});Y(a,"mouseout",function(){this.style.borderTopColor="#327dc8"})}function S(a){var c="",d;for(d in a)c+=d+": "+a[d]+";";return c}function wa(a){var c=a.className=="wumii-popup-item",d=c?a.getElementsByTagName("a")[0]:a,j=d.className,b=d.style.cssText,e=d.innerHTML,k=d.getAttribute("redirectUrl"),o=d.getAttribute("title"),n=d.getAttribute("href"),q=d.onmouseover,l=d.onmouseout,r,h;if(C&&z=="6.0"){var v=d.children[0],u=d.children[1];r=m(d,"width");h=m(d,
"height");if(!r||h=="auto")r=parseInt(m(v,"width"))+parseInt(m(v,"paddingLeft"))*2+parseInt(m(v,"borderWidth"))*2;if(!h||h=="auto")h=parseInt(m(v,"height"))+parseInt(m(v,"paddingTop"))*2+parseInt(m(v,"borderWidth"))*2+parseInt(m(v,"marginBottom"))+parseInt(m(u,"height"));r=parseInt(r)+parseInt(d.style.paddingLeft)*2+"px";h=parseInt(h)+parseInt(d.style.paddingTop)*2+"px"}else h=r="100%";v=w.createElement("div");v.className=j;v.style.cssText=b;v.innerHTML=e;Y(v,"mouseover",q);Y(v,"mouseout",l);j=w.createElement("div");
j.style.cssText=S({position:"absolute",left:"0",top:"0","z-index":2,width:r,height:h,margin:0,padding:0});r=w.createElement("a");r.setAttribute("href",n);r.setAttribute("title",o);r.setAttribute("redirectUrl",k);r.style.cssText=S({"float":"left",width:"100%",height:"100%",background:"url(about:blank)"});j.appendChild(r);v.appendChild(j);d.parentNode.removeChild(d);if(c)a.appendChild(v),a.style.position="relative";return c?a:v}function H(a,b,d){for(var j=d.getAttribute("fromUrl"),e=0;e<a.length;e++){var p=
a[e],k=new String(b),k=k.replace(/{w:(\w+)}/g,function(a,f){return!p[f]?"":(p[f]||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")}),o=w.createElement("div");o.innerHTML=k;k=o.children[0];if(c)o=["b3786b","d2c1a8","d46646","d28fa8","c84f54"],k.children[0].children[0].style.background="#"+o[e%o.length];if(o=k.getElementsByTagName("img")[0])if(c)o.parentNode.removeChild(o),o=s;else{var n=p.thumbnailUrl,h=p.flashUrl;E&&!F&&n==""&&(n="http://app.wumii.com/images/blogWidget/ad_default.jpg");
n?o.setAttribute("image-url",n):h&&(o.setAttribute("flash-url",h),k=wa(k))}if(k.className=="wumii-text-li"&&k.getElementsByTagName("span")[0]&&(n=k.getElementsByTagName("span")[0],n.className=="wumii-hot-item"&&(n.appendChild(w.createTextNode(e+1)),e<3)))n.style.backgroundPosition="-16px 0";n=k;n.nodeName!=="A"&&(n=n.getElementsByTagName("a")[0]);h=p.clickUrl;(p.openInNewWindow||h)&&n.setAttribute("target","_blank");o&&h&&ga(n);d.appendChild(k);u(n,j);k.className==="wumii-popup-item"&&M(k)}}function ha(a,
c,d,b,e){var h=c.children[0];if(e)c.className=e;if(b)h.innerHTML=b;H(a,d,c.children[1]);return c}function ia(a,c,d){if(d.length==0)return"";var b=w.createElement("div");b.innerHTML=a;a=b.children[0];H(d,c,(a.lastElementChild||a.lastChild).children[0]);w.body.appendChild(a);c=a.getAttribute("wid");d=a.children[0];b=a.lastElementChild||a.lastChild;a.style[c]=-b.offsetWidth+"px";if(!a.style.width)a.style.width=b.offsetWidth+d.offsetWidth+"px";if(b.offsetHeight<132)b.style.height="132px";(new Aa(a,c)).g();
return a}function xa(a,c){var d=a.lastElementChild||a.lastChild,b=d.lastElementChild||d.lastChild;if(b.className=="wumii-footer"){var e=b.children[1];if(e){var h=parseInt(d.getAttribute("wmode")),k=e.getAttribute("item-width"),d=e.getAttribute("wsrc"),o=new Image;o.onload=function(){if(h!=1&&c>0){var a=b.offsetWidth+1;a>0&&a/k<c&&(c=parseInt(a/k));b.style.width=k*c-1+"px"}o.parentNode.removeChild(o)};b.appendChild(o);b.removeChild(e);o.src=d}b.children[0].style.display="inline"}}function T(a){if(a)for(var a=
a.getElementsByTagName("img"),b=0;b<a.length;b++){var d=a[b];if(d&&d.className=="wumii-image"){var c=d.getAttribute("image-url"),e=d.getAttribute("flash-url");if(c)d.onload=function(){var a,f,d=this.width;f=this.height;var c=this.parentNode.offsetWidth-6,b=this.parentNode.offsetHeight-6;d/c>f/b?(a=d*b/f,f=b):(a=c,f=f*c/d);var e=(a-c)/2,j=(f-b)/2,d=this.style;d.left=-e+2+"px";d.top=-j+2+"px";d.width=a+"px";d.height=f+"px";d.clip="rect("+j+"px "+(e+c)+"px "+(j+b)+"px "+e+"px)";if(window.XMLHttpRequest==
void 0&&ActiveXObject!=void 0){a=this.parentNode.getElementsByTagName("shape");for(c=0;c<a.length;c++)a[c].style.display="none"}d.visibility="visible"},d.onerror=function(){this.onerror="";this.src=ca()},d.src=c||ca();else if(e)c=d.parentNode,d.style.display="none",c.insertAdjacentHTML("beforeEnd","<object classid='clsid:d27cdb6e-ae6d-11cf-96b8-444553540000' codebase='http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,0,0' width='100%' height='100%' align='center'><param name='allowScriptAccess' value='sameDomain' /><param name='movie' value='"+
e+"' /><param name='quality' value='high' /><param name='wmode' value='transparent' /><embed src='"+e+"' quality='high' wmode='transparent' width='100%'  height='100%' align='center' allowScriptAccess='sameDomain'  type='application/x-shockwave-flash' pluginspage='http://www.macromedia.com/go/getflashplayer' /></object>")}}}function ja(a,c){a.appendChild(c.html);xa(a,c.itemsSize);T(a)}function ka(a,c){for(var d="[node-type=hidden-btn]".match(/^\[([a-z|-]+)=([a-z|-]+)]$/),b=d[1],d=d[2],e=a.children,
h=0;h<e.length;h++){var k=e[h];if(k.getAttribute(b)==d)k.style.visibility=c}}function ga(a){a.className&&(a.className+=" ");a.className+="wumii-widget-ad"}function ya(a){if(a!=""){var c=w.createElement("div");c.innerHTML=a;var d=c.children[0];ga(d);Y(d,"click",function(a){a=a||window.event;if(!a.target)a.target=a.srcElement;if(a.target.nodeName=="A"&&a.target.getAttribute("action-type")=="close")d.style.display="none"});Z(d,"mouseenter",function(){ka(d,"visible")});Z(d,"mouseleave",function(){ka(d,
"hidden")});w.body.appendChild(d)}}var D=O[0].b(),za=O[0].d(),fa=t,la=t;this.init=function(b,e,d,j,l,p,k,o){var d=da(d),n;var q=d.mainItems;n=d.outboundItems;var m=q.length;if(m==0)n="";else{var r=w.createElement("div");r.id="wumiiTemplateHtml";r.innerHTML=b;var b=r.children[0],r=b.lastElementChild||b.lastChild,u=b.children[0],q=ha(q,u.cloneNode(g),e);b.insertBefore(q,r);n instanceof Array&&n.length>0&&(q=ha(n,u.cloneNode(g),e,"\u6765\u81ea\u65e0\u89c5\u7f51\u7edc\u7684\u76f8\u5173\u6587\u7ae0","wumii-external"),
b.insertBefore(q,r),m=Math.max(m,n.length));b.removeChild(u);n={html:b,itemsSize:m}}if(n!=""){q=w.getElementsByTagName("div");m=[];for(b=0;b<q.length;b++)q[b].className==P&&m.push(q[b]);if(m.length==1){q=m[0];m=w.getElementById("wumiiDisplayDiv");if(typeof wumiiEnableCustomPos=="undefined"||!wumiiEnableCustomPos||!m)m=q;(q=w.getElementById("wumiiLikeRecBtnDiv"))?q.innerHTML=j:m.innerHTML=j;ja(m,n);if(l!="")j=w.createElement("style"),j.type="text/css",j.styleSheet?(style.media="screen",j.styleSheet.cssText=
l):j.appendChild(w.createTextNode(l)),l=w.getElementsByTagName("head")[0],l.insertBefore(j,l.firstChild);if(!c){if(E&&!F){if(e=!h){a:{e=w.getElementsByTagName("meta");k=0;for(l=e.length;k<l;k++)if(p=e[k],p.name=="viewport"){e=g;break a}e=/^http:\/\/3g\..*/.test(location.href)}e=!e}if(e)e=w.createElement("a"),p=V+"mobile/related_items?url="+encodeURIComponent(D)+"&title="+encodeURIComponent(za),typeof wumiiSitePrefix!="undefined"&&wumiiSitePrefix&&(p+="&sitePrefix="+encodeURIComponent(wumiiSitePrefix)),
e.style.cssText=S({position:"fixed",right:"0",bottom:"18%","z-index":"2147483646",width:"1em",height:"auto",margin:"0",padding:"15px 10px","line-height":"1.25",border:"1px solid #3f7dbc",background:"#286eb4",color:"#e0e7f1","text-align":"center","text-decoration":"none","font-size":"2.5em","border-top-left-radius":"10px","border-bottom-left-radius":"10px"}),e.innerHTML="\u731c\u4f60\u559c\u6b22",e.setAttribute("href",p),w.body.appendChild(e)}else d.popupItems&&T(ia(p,k||e,d.popupItems));E||ya(o)}}else for(o=
0;o<m.length;o++){a:{e=R;p=m[o].getElementsByTagName("input");for(k=0;k<p.length;k++)if(p[k].getAttribute("name")==e){e=p[k].getAttribute("value");break a}e=s}if(e==a){ja(m[o],n);break}}}};this.initButtons=function(){var a=w.getElementById("wumiiLikeBtnDiv"),b=w.getElementById("wumiiRecommendBtnDiv");btnsDiv=w.getElementById("wumiiBtnDiv");if(a&&b)a.style.marginLeft=(btnsDiv.scrollWidth-a.scrollWidth-b.scrollWidth)/2+"px",L(a),Q(b)};this.initPopupHotItems=function(a,b,c){T(ia(a,b,da(c)))};this.loadPopupHotItems=
function(a){if((!E||F)&&!la){la=g;if(!D)D=location.href;a=V+"widget/popup/hot?obAdIds="+encodeURIComponent(a)+"&url="+encodeURIComponent(D);typeof wumiiSitePrefix!="undefined"&&wumiiSitePrefix&&(a+="&sitePrefix="+encodeURIComponent(wumiiSitePrefix));l(a)}}};})();
